package Presentación;

import Control.Validaciones;
import Datos.Album;
import Datos.Artista;
import Datos.Cancion;
import Datos.CargarDatos;
import Datos.Conexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class Interfaz extends javax.swing.JFrame {
	
	Validaciones v = new Validaciones();
	Conexion conn;
	CargarDatos CD;	
	Album al = new Album();
	Artista ar = new Artista();
	Cancion ca = new Cancion();
	FileInputStream fis;
	int longitudBytes;
	
	public Interfaz() {
		initComponents();
		Validaciones();
		CD = new CargarDatos();	
		setLocationRelativeTo(null);
		tf_cancion.requestFocusInWindow();	
	}	
	
	public final void Validaciones(){
		//Panel uno
		v.validarSoloLetras(tf_nomArtista);
		v.validarSoloLetras(tf_nomAlbum);
		v.validarSoloLetras(tf_nomCancion);
		v.validarLetras(tArea_letra);
		v.validarCaracteresEspeciales(tf_codArtista);
		v.validarCaracteresEspeciales(tf_codAlbum);
		//Panel dos
		v.validarSoloLetras(tf_artista);
		v.validarSoloLetras(tf_cancion);		
	}
	
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_cover = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaLetra = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        tf_cancion = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lbl_cancion = new javax.swing.JLabel();
        btn_consultanew = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        tf_codAlb = new javax.swing.JTextField();
        tf_codArt = new javax.swing.JTextField();
        tf_artista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_artista = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_imagen = new javax.swing.JLabel();
        btn_subirImagen = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tArea_letra = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_nomAlbum = new javax.swing.JLabel();
        lbl_nomCancion = new javax.swing.JLabel();
        tf_nomAlbum = new javax.swing.JTextField();
        tf_nomCancion = new javax.swing.JTextField();
        tf_codAlbum = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cbx_genero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_nomArtista = new javax.swing.JLabel();
        tf_codArtista = new javax.swing.JTextField();
        tf_nomArtista = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lbl_letra = new javax.swing.JLabel();
        MyName1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFocusable(false);

        lbl_cover.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtareaLetra.setEditable(false);
        txtareaLetra.setColumns(20);
        txtareaLetra.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtareaLetra.setRows(5);
        jScrollPane1.setViewportView(txtareaLetra);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf_cancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cancionActionPerformed(evt);
            }
        });
        tf_cancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cancionKeyTyped(evt);
            }
        });

        btn_buscar.setText("Buscar ");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_cancion.setText("Canción");

        btn_consultanew.setText("Nueva búsqueda");
        btn_consultanew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultanewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_cancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultanew, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cancion))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_consultanew))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf_codAlb.setEditable(false);

        tf_codArt.setEditable(false);

        tf_artista.setEditable(false);

        jLabel3.setText("Código Album");

        jLabel2.setText("Código Artista");

        lbl_artista.setText("Artista");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbl_artista))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codArt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_artista))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_codArt))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_codAlb))
                .addGap(14, 14, 14))
        );

        btn_modificar.setText("Modificar datos");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar información");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btnReporte.setText("PDF");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_eliminar)
                        .addGap(1, 1, 1)
                        .addComponent(btnReporte)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_modificar)
                            .addComponent(btn_eliminar)
                            .addComponent(btnReporte)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_cover, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_imagen.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(lbl_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 210));

        btn_subirImagen.setText("Subir imagen");
        btn_subirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirImagenActionPerformed(evt);
            }
        });
        jPanel1.add(btn_subirImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.setEnabled(false);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 95, -1));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 97, -1));

        tArea_letra.setColumns(20);
        tArea_letra.setRows(5);
        tArea_letra.setTabSize(5);
        tArea_letra.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tArea_letraCaretUpdate(evt);
            }
        });
        jScrollPane4.setViewportView(tArea_letra);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 310, 200));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Código Album");

        lbl_nomAlbum.setText("Nombre album");

        lbl_nomCancion.setText("Nombre Canción");

        tf_nomAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nomAlbum.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_nomAlbumCaretUpdate(evt);
            }
        });
        tf_nomAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomAlbumKeyTyped(evt);
            }
        });

        tf_nomCancion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_nomCancionCaretUpdate(evt);
            }
        });
        tf_nomCancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomCancionKeyTyped(evt);
            }
        });

        tf_codAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codAlbumKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nomCancion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nomAlbum, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nomAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_nomAlbum)
                    .addComponent(tf_nomAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nomCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomCancion))
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 330, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbx_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un género musical", "POP", "ROCK", "VALLENATO", "REGGAETON", " " }));

        jLabel1.setText("Género");

        jLabel4.setText("Código Artista");

        lbl_nomArtista.setText("Nombre artista");

        tf_codArtista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codArtistaKeyTyped(evt);
            }
        });

        tf_nomArtista.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tf_nomArtistaCaretUpdate(evt);
            }
        });
        tf_nomArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomArtistaActionPerformed(evt);
            }
        });
        tf_nomArtista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nomArtistaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomArtistaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nomArtista, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nomArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_codArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_nomArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nomArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_codArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_genero))
                .addGap(116, 116, 116))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 300, 120));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_letra.setText("Letra de canción");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(lbl_letra)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_letra)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 330, 240));

        MyName1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        MyName1.setText("Created by Wilson De la Hoz.");
        jPanel1.add(MyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jTabbedPane1.addTab("Ingreso de datos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codAlbumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codAlbumKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_codAlbumKeyTyped

    private void tf_codArtistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codArtistaKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_codArtistaKeyTyped

    private void tArea_letraCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tArea_letraCaretUpdate
        validarDatosIngresados();
    }//GEN-LAST:event_tArea_letraCaretUpdate

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        limpiarIngreso();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
	String codArtista = tf_codArtista.getText().trim();
        String artista = tf_nomArtista.getText().trim();
        String genero = cbx_genero.getSelectedItem().toString();
        String codAlbum = tf_codAlbum.getText().trim();
        String album = tf_nomAlbum.getText().trim();
	String cancion = tf_nomCancion.getText().trim();
        String letra = tArea_letra.getText().trim();
		
        //Se envían los datos
        al.setCod_album(codAlbum);
        al.setNom_album(album);
        ar.setCod_artista(codArtista);
        ar.setNom_artista(artista);
        ar.setGen_artista(genero);
        ca.setNom_canciones(cancion);
        ca.setLetra_canciones(letra);
        al.setFis(fis);
        al.setLongitudBytes(longitudBytes);
        
        CD.insertarDatos(al, ar, ca);
        limpiarIngreso();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tf_nomCancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomCancionKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_nomCancionKeyTyped

    private void tf_nomCancionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_nomCancionCaretUpdate
        validarDatosIngresados();
    }//GEN-LAST:event_tf_nomCancionCaretUpdate

    private void tf_nomAlbumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomAlbumKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_nomAlbumKeyTyped

    private void tf_nomAlbumCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_nomAlbumCaretUpdate
        validarDatosIngresados();
    }//GEN-LAST:event_tf_nomAlbumCaretUpdate

    private void tf_nomArtistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomArtistaKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_nomArtistaKeyTyped

    private void tf_nomArtistaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomArtistaKeyReleased
		//
    }//GEN-LAST:event_tf_nomArtistaKeyReleased

    private void tf_nomArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomArtistaActionPerformed

    private void tf_nomArtistaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tf_nomArtistaCaretUpdate
        validarDatosIngresados();
    }//GEN-LAST:event_tf_nomArtistaCaretUpdate

    private void btn_subirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirImagenActionPerformed
       cargarImagen();
    }//GEN-LAST:event_btn_subirImagenActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            consultarCancion();
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tf_cancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cancionKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_cancionKeyTyped

    private void tf_cancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cancionActionPerformed
        //
    }//GEN-LAST:event_tf_cancionActionPerformed

    private void btn_consultanewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultanewActionPerformed
        limpiarConsulta();
    }//GEN-LAST:event_btn_consultanewActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

		String nombreCancion = tf_cancion.getText();
		String mensaje = "¿Desea borrar la canción " + nombreCancion.toUpperCase() + "?";
		int resp = JOptionPane.showConfirmDialog(null, mensaje, "Seleccione una opción", JOptionPane.YES_NO_OPTION);
		if(resp == 0){
			borrarCancion();
			limpiarConsulta();
		}else{
			//Nothing to do			
		}		
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
		//Nothing to do yet
    }//GEN-LAST:event_btnReporteActionPerformed

	//Llama al JDialog
    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
 
        UpdateDialog ud = new UpdateDialog(this, true);
        ud.setLocationRelativeTo(this);
        ud.setVisible(true);
        ud.in.tf_cancion.getText();
    }//GEN-LAST:event_btn_modificarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	
	public static Conexion hc;
	
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interfaz().setVisible(true);
			}
		});
	}	
	
	public void validarDatosIngresados(){
		String artista = tf_nomArtista.getText().trim();
		String album = tf_nomAlbum.getText().trim();
		String cancion = tf_nomCancion.getText().trim();
		String letra = tArea_letra.getText().trim();
		String genero = (String) cbx_genero.getSelectedItem();
		String codArtista = tf_codArtista.getText();
		String codAlbum = tf_codAlbum.getText();
		
		//Habilida el botón 'Guardar'
		if(longitudBytes == 0 || artista.isEmpty() || album.isEmpty() || cancion.isEmpty() || letra.isEmpty() || genero.isEmpty() || codArtista.isEmpty() || codAlbum.isEmpty()){
			btn_guardar.setEnabled(false);
		}else{
			btn_guardar.setEnabled(true);
		}
	}
	
	public void limpiarIngreso(){
		tf_nomArtista.setText("");
		tf_nomAlbum.setText("");
		tf_nomCancion.setText("");
		tArea_letra.setText("");
		cbx_genero.setSelectedIndex(0);
		tf_codArtista.setText("");
		tf_codAlbum.setText("");
		lbl_imagen.setIcon(null);
	}
	
	public void limpiarConsulta(){
		tf_artista.setText("");
		tf_codAlb.setText("");
		tf_codArt.setText("");
		tf_cancion.setText("");
		txtareaLetra.setText("");
		lbl_cover.setIcon(null);
	}
	
	private void cargarImagen(){
		JFileChooser j =  new JFileChooser();
		FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");
		j.setFileFilter(filtro);		
		int estado = j.showOpenDialog(null);
		if(estado == JFileChooser.APPROVE_OPTION){			
			try {
				fis = new FileInputStream(j.getSelectedFile());
				this.longitudBytes = (int) j.getSelectedFile().length();
				lbl_imagen.setEnabled(true);
				try {
					lbl_imagen.setIcon(null);				
					Image icono = ImageIO.read(j.getSelectedFile()).getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT);
					lbl_imagen.setIcon(new ImageIcon(icono));
					lbl_imagen.updateUI();
					} catch (IOException ex) {
						JOptionPane.showMessageDialog(null, "Error, no se pudo cargar la imagen " + ex);
					}				
			} catch (FileNotFoundException e) {
				JOptionPane.showMessageDialog(null, "Error, archivo no encontrado " + e);
			}
		}
	}
	
		public void consultarCancion() throws SQLException {
		String sql = "select letra_canciones, album.cod_album, album.img_album, artistas.cod_artista, nom_artista from canciones inner join album on album.cod_album = canciones.cod_album "
				+ "inner join artistas on artistas.cod_artista = canciones.cod_artista where nom_canciones like '%" + tf_cancion.getText() + "%'";

		conn = new Conexion();
		Statement st = conn.conn.createStatement();
		ResultSet rs = st.executeQuery(sql);
		InputStream is;		
		//Boolean existeRegistro = false;
		String valor = tf_cancion.getText();
			try {
				if(valor.isEmpty()){
					JOptionPane.showMessageDialog(null, "Ingrese el nombre de alguna canción para buscar");
				}else {
					if(rs.next()){
								
							tf_artista.setText(rs.getString("nom_artista"));
							tf_codArt.setText(rs.getString("cod_artista"));
							tf_codAlb.setText(rs.getString("cod_album"));
							txtareaLetra.setText(rs.getString("letra_canciones"));
							//Trayendo la imagen
							is = rs.getBinaryStream("img_album");
							BufferedImage bi = ImageIO.read(is);
							ImageIcon foto = new ImageIcon(bi);
							Image img = foto.getImage();
							Image newimg = img.getScaledInstance(lbl_cover.getWidth(), lbl_cover.getHeight(), Image.SCALE_SMOOTH);
							ImageIcon newicon = new ImageIcon(newimg);
							lbl_cover.setIcon(newicon);
							lbl_cover.updateUI();

					}else{
						JOptionPane.showMessageDialog(null, "Error, no hay registros");
					}
				}
			} catch (HeadlessException | IOException | SQLException e) {
				JOptionPane.showMessageDialog(null, "Error " + e);
			}finally{
				conn.desconectar();
				System.out.println("Desconectado después de consultar la canción");
			}
	}
	
	public void borrarCancion(){
		conn = new Conexion();
		String nomCancion = tf_cancion.getText();
		String query = "delete canciones, album, artistas from canciones inner join album on album.cod_album "
				+ "= canciones.cod_album inner join artistas on artistas.cod_artista = canciones.cod_artista "
				+ "where nom_canciones like '%" + nomCancion + "%'";
		try {
			PreparedStatement st = conn.conn.prepareStatement(query);
			st.executeUpdate();
			String cadena = "Se eliminó la canción: " + nomCancion.toUpperCase();
			JOptionPane.showMessageDialog(null, cadena);
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "No se pudo borrar el registro " + e);
		}finally{
			conn.desconectar();
			System.out.println("Desconectado después de borrar canción");
		}
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MyName1;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_consultanew;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_subirImagen;
    private javax.swing.JComboBox<String> cbx_genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_artista;
    private javax.swing.JLabel lbl_cancion;
    private javax.swing.JLabel lbl_cover;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_letra;
    private javax.swing.JLabel lbl_nomAlbum;
    private javax.swing.JLabel lbl_nomArtista;
    private javax.swing.JLabel lbl_nomCancion;
    private javax.swing.JTextArea tArea_letra;
    public javax.swing.JTextField tf_artista;
    public static javax.swing.JTextField tf_cancion;
    public javax.swing.JTextField tf_codAlb;
    private javax.swing.JTextField tf_codAlbum;
    public javax.swing.JTextField tf_codArt;
    private javax.swing.JTextField tf_codArtista;
    private javax.swing.JTextField tf_nomAlbum;
    private javax.swing.JTextField tf_nomArtista;
    private javax.swing.JTextField tf_nomCancion;
    private javax.swing.JTextArea txtareaLetra;
    // End of variables declaration//GEN-END:variables
}
