
package Presentación;

import Control.Validaciones;
import Datos.Album;
import Datos.Artista;
import Datos.Cancion;
import Datos.Conexion;
import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Wilson
 */
public class UpdateDialog extends javax.swing.JDialog {
	
	Interfaz in;
	Album al = new Album();
	Artista ar = new Artista();
	Cancion ca = new Cancion();
	Validaciones v = new Validaciones();
	FileInputStream fis;
	int longitudBytes;
	private Conexion con;
	private PreparedStatement ps;
	String nombreCancion;

	/**
	 * Creates new form UpdateDialog2
	 */
	public UpdateDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}
	
	//Otro constructor para poder hacer las validaciones al iniciar el JDialog
	public UpdateDialog(){
		Validaciones();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_imgUpdate = new javax.swing.JLabel();
        btn_imgUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_artistaUpdate = new javax.swing.JLabel();
        tf_artistaUpdate = new javax.swing.JTextField();
        tf_codArtUpdate = new javax.swing.JTextField();
        lbl_codArtUpdate = new javax.swing.JLabel();
        lbl_genArtUpdate = new javax.swing.JLabel();
        cbx_genUpdate = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lbl_albumUpdate = new javax.swing.JLabel();
        tf_albumUpdate = new javax.swing.JTextField();
        tf_codAlUpdate = new javax.swing.JTextField();
        tf_cancionUpdate = new javax.swing.JTextField();
        lbl_codAlUpdate = new javax.swing.JLabel();
        lbl_cancionUpdate = new javax.swing.JLabel();
        lbl_letraUpdate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea_letraUpdate = new javax.swing.JTextArea();
        btn_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbl_imgUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_imgUpdate.setText("Subir imagen");
        btn_imgUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imgUpdateActionPerformed(evt);
            }
        });

        lbl_artistaUpdate.setText("Artista:");

        tf_artistaUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_artistaUpdateKeyTyped(evt);
            }
        });

        tf_codArtUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codArtUpdateKeyTyped(evt);
            }
        });

        lbl_codArtUpdate.setText("Código:");

        lbl_genArtUpdate.setText("Género:");

        cbx_genUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opción", "Pop", "Rock", "Vallenato", "Reggaeton", "Hip Hop" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_artistaUpdate)
                        .addComponent(lbl_codArtUpdate))
                    .addComponent(lbl_genArtUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_codArtUpdate)
                    .addComponent(tf_artistaUpdate)
                    .addComponent(cbx_genUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_artistaUpdate)
                    .addComponent(tf_artistaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codArtUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codArtUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_genArtUpdate)
                    .addComponent(cbx_genUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lbl_albumUpdate.setText("Album:");

        tf_albumUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_albumUpdateKeyTyped(evt);
            }
        });

        tf_codAlUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codAlUpdateKeyTyped(evt);
            }
        });

        tf_cancionUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cancionUpdateKeyTyped(evt);
            }
        });

        lbl_codAlUpdate.setText("Código:");

        lbl_cancionUpdate.setText("Canción:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cancionUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_codAlUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_albumUpdate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cancionUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(tf_codAlUpdate)
                    .addComponent(tf_albumUpdate))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_albumUpdate)
                    .addComponent(tf_albumUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codAlUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codAlUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cancionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cancionUpdate))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lbl_letraUpdate.setText("Letra de la canción:");

        tarea_letraUpdate.setColumns(20);
        tarea_letraUpdate.setRows(5);
        jScrollPane1.setViewportView(tarea_letraUpdate);

        btn_update.setText("Actualizar datos");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_imgUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btn_imgUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbl_letraUpdate)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_imgUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_letraUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_imgUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_update)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imgUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imgUpdateActionPerformed
        updateImagen();
    }//GEN-LAST:event_btn_imgUpdateActionPerformed

    private void tf_artistaUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_artistaUpdateKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_artistaUpdateKeyTyped

    private void tf_albumUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_albumUpdateKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_albumUpdateKeyTyped

    private void tf_cancionUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cancionUpdateKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_cancionUpdateKeyTyped

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // Obtengo los datos ingresados en los TextFields		
		String artista = tf_artistaUpdate.getText();
		String codArtista = tf_codArtUpdate.getText();
		String genArtista = cbx_genUpdate.getSelectedItem().toString();
		String album = tf_albumUpdate.getText();
		String codAlbum = tf_codAlUpdate.getText();
		String cancion = tf_cancionUpdate.getText();
		String letra = tarea_letraUpdate.getText();
		//Se envían los datos
		ar.setNom_artista(artista);
		ar.setCod_artista(codArtista);
		ar.setGen_artista(genArtista);
		al.setNom_album(album);
		al.setCod_album(codAlbum);
		ca.setNom_canciones(cancion);
		ca.setLetra_canciones(letra);
		al.setFis(fis);
		al.setLongitudBytes(longitudBytes);
				
		updateDatos(al, ar, ca);		
    }//GEN-LAST:event_btn_updateActionPerformed

    private void tf_codArtUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codArtUpdateKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_codArtUpdateKeyTyped

    private void tf_codAlUpdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codAlUpdateKeyTyped
        v.toMayusculas(evt);
    }//GEN-LAST:event_tf_codAlUpdateKeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UpdateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UpdateDialog dialog = new UpdateDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
	
	public final void Validaciones(){
		v.validarSoloLetras(tf_artistaUpdate);
		v.validarSoloLetras(tf_cancionUpdate);
		v.validarSoloLetras(tf_albumUpdate);
		v.validarLetras(tarea_letraUpdate);
		v.validarCaracteresEspeciales(tf_codAlUpdate);
		v.validarCaracteresEspeciales(tf_codArtUpdate);
	}
	
	private void updateImagen(){
		JFileChooser j =  new JFileChooser();
		FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG & PNG", "jpg", "png");
		j.setFileFilter(filtro);		
		int estado = j.showOpenDialog(null);
		if(estado == JFileChooser.APPROVE_OPTION){			
			try {
				fis = new FileInputStream(j.getSelectedFile());
				this.longitudBytes = (int) j.getSelectedFile().length();
				lbl_imgUpdate.setEnabled(true);
				try {
					lbl_imgUpdate.setIcon(null);				
					Image icono = ImageIO.read(j.getSelectedFile()).getScaledInstance(lbl_imgUpdate.getWidth(), lbl_imgUpdate.getHeight(), Image.SCALE_DEFAULT);
					lbl_imgUpdate.setIcon(new ImageIcon(icono));
					lbl_imgUpdate.updateUI();
					} catch (IOException ex) {
						JOptionPane.showMessageDialog(null, "Error, no se pudo cargar la imagen " + ex);
					}				
			} catch (FileNotFoundException e) {
				JOptionPane.showMessageDialog(null, "Error, archivo no encontrado " + e);
			}
		}
	}
	
	public void updateDatos(Album al, Artista ar, Cancion ca) {
		nombreCancion = Interfaz.tf_cancion.getText();
		String query = "update canciones inner join album on album.cod_album = canciones.cod_album inner join artistas on artistas.cod_artista = canciones.cod_artista set \n"
				+ "nom_artista = ?, artistas.cod_artista = ?, artistas.gen_artista = ?, nom_album = ?, album.cod_album = ?, \n"
				+ "album.img_album = ?, nom_canciones = ?, letra_canciones = ? where nom_canciones = ?;";
		con = new Conexion();
		try {
			ps = con.getConnection().prepareStatement(query);
			ps.setString(1, tf_artistaUpdate.getText());
			ps.setString(2, tf_codArtUpdate.getText());
			ps.setString(3, cbx_genUpdate.getSelectedItem().toString());
			ps.setString(4, tf_albumUpdate.getText());
			ps.setString(5, tf_codAlUpdate.getText());
			ps.setBinaryStream(6, fis, longitudBytes);
			ps.setString(7, tf_cancionUpdate.getText());
			ps.setString(8, tarea_letraUpdate.getText());
			ps.setString(9, nombreCancion);
			
			int res = ps.executeUpdate();
			if(res > 0){
				JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
				dispose();
			}			
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Error al tratar de actualizar los datos " + e);
			System.err.println("" + e);
		}finally{
			con.desconectar();
			System.out.println("Desconectado desde UpdateDialog");
		}	
	}
	
	
	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imgUpdate;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbx_genUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_albumUpdate;
    private javax.swing.JLabel lbl_artistaUpdate;
    private javax.swing.JLabel lbl_cancionUpdate;
    private javax.swing.JLabel lbl_codAlUpdate;
    private javax.swing.JLabel lbl_codArtUpdate;
    private javax.swing.JLabel lbl_genArtUpdate;
    private javax.swing.JLabel lbl_imgUpdate;
    private javax.swing.JLabel lbl_letraUpdate;
    private javax.swing.JTextArea tarea_letraUpdate;
    private javax.swing.JTextField tf_albumUpdate;
    private javax.swing.JTextField tf_artistaUpdate;
    private javax.swing.JTextField tf_cancionUpdate;
    private javax.swing.JTextField tf_codAlUpdate;
    private javax.swing.JTextField tf_codArtUpdate;
    // End of variables declaration//GEN-END:variables
}
